// Generates one piano-ish tone per octave (C2..C7) plus src/tones.ts.
// The app picks the nearest base and shifts playback rate by at most a few
// semitones, so pitch stays accurate while the rate stays within Android's
// 0.1-2.0 playback-rate limit.
const fs = require('fs');
const path = require('path');

const SAMPLE_RATE = 44100;
const DURATION = 1.1; // seconds
const BASE_OCTAVES = [2, 3, 4, 5, 6, 7];
const C4 = 261.626; // Hz

const HARMONICS = [
  { mult: 1, amp: 1.0 },
  { mult: 2, amp: 0.45 },
  { mult: 3, amp: 0.22 },
  { mult: 4, amp: 0.12 },
];

function renderWav(freq) {
  const N = Math.floor(SAMPLE_RATE * DURATION);
  const samples = new Float32Array(N);
  let peak = 0;
  for (let i = 0; i < N; i++) {
    const t = i / SAMPLE_RATE;
    const attack = Math.min(1, t / 0.004); // 4 ms attack
    const decay = Math.exp(-3.2 * t);
    const env = attack * decay;
    let s = 0;
    for (const h of HARMONICS) {
      // Skip harmonics above Nyquist to avoid aliasing on high octaves.
      if (freq * h.mult < SAMPLE_RATE / 2) {
        s += h.amp * Math.sin(2 * Math.PI * freq * h.mult * t);
      }
    }
    s *= env;
    samples[i] = s;
    if (Math.abs(s) > peak) peak = Math.abs(s);
  }
  const gain = peak > 0 ? 0.9 / peak : 1;

  const bytesPerSample = 2;
  const dataSize = N * bytesPerSample;
  const buffer = Buffer.alloc(44 + dataSize);
  buffer.write('RIFF', 0);
  buffer.writeUInt32LE(36 + dataSize, 4);
  buffer.write('WAVE', 8);
  buffer.write('fmt ', 12);
  buffer.writeUInt32LE(16, 16);
  buffer.writeUInt16LE(1, 20); // PCM
  buffer.writeUInt16LE(1, 22); // mono
  buffer.writeUInt32LE(SAMPLE_RATE, 24);
  buffer.writeUInt32LE(SAMPLE_RATE * bytesPerSample, 28);
  buffer.writeUInt16LE(bytesPerSample, 32);
  buffer.writeUInt16LE(16, 34);
  buffer.write('data', 36);
  buffer.writeUInt32LE(dataSize, 40);
  for (let i = 0; i < N; i++) {
    const v = Math.max(-1, Math.min(1, samples[i] * gain));
    buffer.writeInt16LE(Math.round(v * 32767), 44 + i * bytesPerSample);
  }
  return buffer;
}

const assetsDir = path.join(__dirname, '..', 'assets');
for (const o of BASE_OCTAVES) {
  const freq = C4 * Math.pow(2, o - 4);
  const buf = renderWav(freq);
  const file = path.join(assetsDir, `tone${o}.wav`);
  fs.writeFileSync(file, buf);
  console.log('wrote', file, `(${freq.toFixed(1)} Hz, ${buf.length} bytes)`);
}

// Emit the require map so Metro bundles each file statically.
const lines = BASE_OCTAVES.map(
  (o) => `  ${o}: require('../assets/tone${o}.wav'),`
).join('\n');
const ts = `// AUTO-GENERATED by scripts/gen-tone.js — do not edit by hand.
// Base piano tones keyed by octave (the C of that octave).
export const TONE_OCTAVES = [${BASE_OCTAVES.join(', ')}];

export const TONES: Record<number, number> = {
${lines}
};
`;
fs.writeFileSync(path.join(__dirname, '..', 'src', 'tones.ts'), ts);
console.log('wrote src/tones.ts');
