// AUTO-GENERATED by scripts/gen-tone.js — do not edit by hand.
// Base piano tones keyed by octave (the C of that octave).
export const TONE_OCTAVES = [2, 3, 4, 5, 6, 7];

export const TONES: Record<number, number> = {
  2: require('../assets/tone2.wav'),
  3: require('../assets/tone3.wav'),
  4: require('../assets/tone4.wav'),
  5: require('../assets/tone5.wav'),
  6: require('../assets/tone6.wav'),
  7: require('../assets/tone7.wav'),
};
